### ISSUE TITLE
Console commands executed through ghost_chat

### ISSUE THREAD

**Issue by ThatFridgeFella** [p2sr/SourceAutoRecord#152]
If you type ";[console_command]" and say it in ghost_chat, then the command will be executed. The quotes are required for this to work.

Example: ";quit" would cause the player to quit out of the game.

**Comment by ThisAMJ** [comment]
Do you mean the sender or reciever will execute the command

**Comment by mlugg** [comment]
I know about this, and unfortunately it can't be solved as long as we're using the game chat UI for this: it's a bug with the game, it happens with normal co-op chat too. I'm going to close this because while it isn't ideal there's not really a *solution* to it (short of writing our own chat UI, which... yeah no sorry)
