### ISSUE TITLE
SAR Not Unloading properly, cannot load more than once

### ISSUE THREAD

**Issue by TheNodeDev** [p2sr/SourceAutoRecord#186]
```
] plugin_load sar
Loaded SourceAutoRecord, Version 1.12.7
Loaded plugin "sar"
] plugin_unload sar
Cya :)
Unloaded plugin "0"
] plugin_load sar
SAR: Game not supported!
SAR: Failed to load SourceAutoRecord!
Failed to load plugin "sar"
Unable to load plugin "sar"
```
^ Console Output from a verified, updated vanilla Portal 2

prior to this, I was playing around with custom code in the plugins, i thought I broke something, but using the latest release of SAR it appears to be an overall SAR issue.

How to reproduce:
- Open Portal 2
- Load SAR
- Unload SAR
- Attempt To Load SAR Again

**Comment by Krzyhau** [comment]
Could you specify the platform you're using? I've checked this issue on Windows, using release version, pre-release version and a fresh build of the master branch, and for all of them reloading the plugin through the steps you've given worked fine.

Additionally, see if the issue is present for you in the latest pre-release, or the fresh build of master branch, as the latest release (1.12.7) happened pretty long time ago and I believe this issue was addressed multiple times on Discord over that time, so there's a good chance whatever you're experiencing has been fixed already.

**Comment by TheNodeDev** [comment]
I'm on Windows 10
[Here is a video showing my issue](https://youtu.be/inbYcwi43R8)

My portal 2 install is fresh from earlier today

I'm cloning from the master and building it, the same behavior occurs with most other releases i could find on the github

(Not quite sure why the plugin was called 'binary', probably an issue with the copy.bat, but is unrlated and has not happened before)
