### ISSUE TITLE
[bug] reload does not use fast loads

### ISSUE THREAD

**Issue by mlugg** [p2sr/SourceAutoRecord#4]
The `reload` command doesn't obey `sar_loads_uncap` nor `sar_loads_norender`.

Transferred from Blenderiste09/SourceAutoRecord#53

**Comment by Krzyhau** [comment]
It would be nice to clarify where that assumption comes from. It seems like `reload` and `restart` commands are doing the session shutdown in addition to reloading the game, so longer loads are expected when using those. 

Both `sar_loads_uncap` and `sar_loads_norender` seems to function properly when using these commands - the `fps_max` and `mat_norendering` values are set and reset properly at the beginning and end of the loading as a result of using these commands. 

The additional loading time happens while command's behavior is in function, meaning it comes from something these commands have no affect on. Unless we want to look into making these commands function, I don't see a reason to keep this issue open, especially since it's not the plugin's fault and there are faster alternatives (`restart_level`). Waiting for Rex (who have made the original issue post) to respond and then I'll close it.

**Comment by Krzyhau** [comment]
Got a response. I think we're fine to close this one.
