### ISSUE TITLE
[bug/suggestion] lphud resets itself back to zero when typing sar_lphud 0

### ISSUE THREAD

**Issue by AyumiToshiyuki** [p2sr/SourceAutoRecord#42]
Hiding the lphud shouldn't reset it back to zero, it could be useful for least portals runs to keep track of how many portal you've placed, even when hiding the HUD. It should only be possible to reset it by typing "sar_lphud_set 0".

How to reproduce:
```
sar_lphud 1
shoot portals to increase counter
sar_lphud 0
sar_lphud 1
and now it says "Portals: 0" even though sar_lphud_set 0 hasn't been used.
```

Again, I don't know if this is a bug or an intended feature, but I often hide HUD in my runs during cutscenes, and I'd like to still be able to keep track of how many portals I've placed.

**Comment by mlugg** [comment]
The main weird thing here would be turning on lphud for the first time after playing the game for a while; since lphud being hidden wouldn't stop it counting up, it'd already have a high value, which would be pretty unintuitive. Maybe there could be an additional cvar `sar_lphud_show` which purely affects rendering.
