### ISSUE TITLE
[suggestion] smooth veccam strafing

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#71]
Idea: Add some smoothing to veccam strafe type, so just strafing forward doesn't shake the view
It doesn't have to be much, just average the last tick(s)'s velang and the current velang.

**Comment by Krzyhau** [comment]
I don't see the point of actually interpolating the angles. If the point is to make the smooth-looking TASes, why using veccam on a straight line in the first place?

I solved it by automatically switching veccam to regular vectorial strafing after the turn has been completed: c214f94720aee38be0934ea8b2ba8be137269bf2

It seems that it was the original intention from the beginning (hence why veccam actually checks the target angle and not velocity angle when going in a straight line), but line following algorithm is resetting itself once in a while, which caused these angle flickers. It is intentional though - without resetting it would be easy for an autostrafer to take a wobbly path, which could make movement not optimal.
